app = "3d-portfolio-builder"
primary_region = "ord"
PORT = "8080"

[http_service]
  internal_port = 80  # Change from 3000 to 80 for Nginx
  force_https = true
  auto_stop_machines = "stop"
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[vm]]
  memory = "1gb"
  cpu_kind = "shared"
  cpus = 1
