# fly.toml app configuration file generated for render-cove on 2025-02-19T18:42:40-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'render-cove'
primary_region = 'ord'

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
